### ISSUE TITLE
👀Look into and identify 🚨alerts integration

### ISSUE THREAD

**Issue by dannytsang** [dannytsang/homeassistant-config#14]
Look into replacing some of the notifictions with [alerts](https://www.home-assistant.io/integrations/alert/) instead as mentioned by @alphasixtyfive [here](https://twitter.com/alphasixtyfive/status/1460289493169229831?s=20).

The integration should make repeated notifications and acknowledgements a lot easier.

Example candidates for replacements:

>   - id: "1622374233310"
>     alias: "^Office: Close Office Curtains At Night"
>     description: ""
>     trigger:
>       - platform: sun
>         event: sunset
>         offset: -01:00:00
>         id: summer
>       - platform: sun
>         event: sunset
>         id: winter
>     condition:
>       - condition: state
>         entity_id: input_boolean.enable_office_curtain_automations
>         state: "on"
>     action:
>       - choose:
>           - conditions:
>               - condition: or
>                 conditions:
>                   - condition: state
>                     entity_id: binary_sensor.office_window_right
>                     state: "on"
>                   - condition: state
>                     entity_id: binary_sensor.office_window_left
>                     state: "on"
>             sequence:
>               - service: script.post_to_home_log
>                 data:
>                   message:
>                     ":warning: :window: Office window is still open so not closing
>                     curtains. before closing curtains. :warning:"

**Comment by dannytsang** [comment]
Turns out alerts are not a replacement for notifications and they are a separate configuration so the above example won't be a direct replacement.

**Comment by alphasixtyfive** [comment]
Yes, you would need to list your notifiers and alerts usually require a binary sensor to get triggered but they are really good at repeated notifications and can also be silenced.

**Comment by alphasixtyfive** [comment]
I ended up ditching **alert** integration since it was not flexible enough for me plus I needed my automations to rely on something other than **notify**:

```
- alias: Evening reminder to take waste bins out
  trigger:
    - platform: time_pattern
      minutes: '/45'
  condition:
    - condition: state
      entity_id: input_boolean.bin_collection_reminder
      state: 'on'
    - condition: time
      after: '18:00'
      before: '22:30'
  action:
      ....
```

**Comment by dannytsang** [comment]
@alphasixtyfive that's the same conclusion I came to as well. I haven't gone much further but looking to use the actionable notifications to replicate silencing the alarm etc. Cheers for the example. I will use that when I get around to creating my own alerts.

**Comment by alphasixtyfive** [comment]
I'm using a bunch of various methods to silence a notification: app action, telegram callback, NFC tag or I'm simply asking Yandex Alisa (Russian Alexa) to do that. 

```
- alias: Bin collection acknowledgement
  trigger:
    - platform: event
      event_type: "tileboard"
      event_data:
        action: "bin_collection_acknowledge"
      id: "tileboard"

    - platform: event
      event_type: telegram_callback
      event_data:
        data: "/bin_collection_acknowledge"
      id: "telegram"

    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: "BIN_COLLECTION_ACKNOWLEDGE"
      id: "mobile_app"

    - platform: tag
      tag_id: 04e6c342-e621-46f3-890f-1cc87a78941f
      id: "tag"

    - platform: event
      event_type: yandex_intent
      event_data:
        text: "Мусорные баки выставлены"
      id: "yandex_intent"
  action:
    - alias: Set up variables
      variables:
        message_en: "Thank you for confirming that waste bins are out"
        message_ru: "Спасибо, что подтвердили, что мусорные баки выставлены"

    - alias: Turn off the reminder
      service: input_boolean.turn_off
      entity_id: input_boolean.bin_collection_reminder

    - alias: Notify family
      service: notify.family
      data:
        message: "🗑 {{ message_en }}"

    - alias: Send a TTS
      service: script.turn_on
      entity_id: script.tts
      data:
        variables:
          message_en: "{{ message_en }}"
          message_ru: "{{ message_ru }}"
```
