### ISSUE TITLE
Dynamic Starting Dashboard

### ISSUE THREAD

**Issue by dannytsang** [dannytsang/homeassistant-config#44]
Create a changing dashboard baased on what is going on. The scope is on the starting page to give relevant information for what is going on. Some of this already exists for #40 however there are more situations when something is relevant especially when something is not right.

Example relevant information:
- [ ] 🤖🧹 Robot vacuum
- [ ] ⛈Severe/bad weather
- [ ] 🚗🚆Travel information
- [ ] 💧🏡House sensors like leaks

**Comment by dannytsang** [comment]
Dynamic card for the vacuum:
```
  - type: custom:mushroom-chips-card
    chips:
      - type: conditional
        conditions:
          - entity: vacuum.t8
            state_not: docked
        chip:
          type: entity
          entity: vacuum.t8
```

**Comment by dannytsang** [comment]
Dynamic card for bad weather:
```
  - type: custom:mushroom-chips-card
    chips:
      - type: conditional
        conditions:
          - entity: sensor.met_office_rss_weather_warnings
            state_not: '0'
        chip:
          type: weather
          entity: weather.openweathermap
          show_conditions: true
          show_temperature: true
```

**Comment by dannytsang** [comment]
Keep getting failed connection trying to use Waze integration with entities.

**Comment by dannytsang** [comment]
Using mushroom conditional chips to show leaks detected.
```
square: false
columns: 1
type: grid
cards:
  - type: grid
    columns: 1
    cards:
      - type: custom:mushroom-chips-card
        chips:
          - type: conditional
            conditions:
              - entity: binary_sensor.conservatory_bucket_water
                state: on
            chip:
              type: entity
              entity: binary_sensor.conservatory_bucket_water
          - type: conditional
            conditions:
              - entity: binary_sensor.kitchen_sink_water
                state: on
            chip:
              type: entity
              entity: binary_sensor.kitchen_sink_water
          - type: conditional
            conditions:
              - entity: binary_sensor.bathroom_water
                state: on
            chip:
              type: entity
              entity: binary_sensor.bathroom_water

**Comment by dannytsang** [comment]
Added more chips if devices are turned on. It's particularly useful for things like white goods that are not in view like our washing machine.

![image](https://user-images.githubusercontent.com/567982/193405871-29e6c9c0-44b7-4122-9564-cf0f23a18cc7.png)

I use a power monitoring device like a smart plug or shelly and if the device draws power over a threshold then it will deem it as on. The template sensor uses the device class **running**.
```
template:
  - trigger:
    binary_sensor:
      - name: "Washing Machine Powered On"
        unique_id: ac5bc0d6-2199-4a2a-8d23-c2f81e8fe0dd
        device_class: "running"
        icon: "mdi:washing-machine{{ '' if states('sensor.washing_machine_current_consumption') | float(0) > 9 else '-off' }}"
        state: "{{ states('sensor.washing_machine_current_consumption') | float(0) > 9 }}"
```

Add the template sensor to a conditional chip like above:
```
type: custom:mushroom-chips-card
chips:
  - type: conditional
    conditions:
      - entity: binary_sensor.washing_machine_powered_on
        state: 'on'
    chip:
      type: entity
      entity: binary_sensor.washing_machine_powered_on
```
