### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by dannytsang** [dannytsang/homeassistant-config#46]
Error message:
`WARNING (MainThread) [homeassistant.helpers.script] Error in 'choose[0]' evaluation: In 'template' condition: TypeError: object of type 'NoneType' has no len()`

Suspect it's related to this script and trying to handle the different types of parameters that are of exclusive or in nature (only 1 can be set).

```
post_to_slack_with_attachments:
    alias: "Post To Slack Home Log With File Or URL Attachments"
    icon: mdi:slack
    description: "Post a message with a file or URL attachment to the home_log 
    channel. Only a file or URL can be set. Not both or neither. Please use a 
    send script to decouple from the messaging platform."
    fields:
      message:
        description: Message to post
        required: true
      title:
        description: (optional)Title to the message posted.
      target:
        description: "Slack channel to post to including the #"
        required: true
        example: "#general"
      filePath:
        description: File path to attach to post.
      url:
        description: Link to file.
        example: "https://picsum.photos/200/300"
    sequence:
      - choose:
        # Check at least filePath or url is set.
        - conditions:
            - condition: template
              value_template: "{{ filePath is not defined and url is not defined }}"
          sequence:
            - service: script.send_direct_notification
              data:
                message: ":warning: File or URL not set. Original messsage:\n{{ message}}"
                title: "Missing file or URL for Slack"
                people: person.danny
        - conditions:
            - condition: template
              value_template: "{{filePath is defined and url is defined }}"
          sequence:
            - service: script.send_direct_notification
              data:
                message: ":warning: File and URL are set when only one or the other can.
                Original messsage:\n{{ message}}"
                title: "Missing file or URL for Slack"
                people: person.danny
        # If a filePath is set.
        - conditions:
            - condition: template
              value_template: "{{filePath is defined and url is not defined }}"
          sequence:
            - service: notify.slack_notify
              data:
                message: "{{ message }}"
                title: "{{ title|default('', true) }}"
                target: "{{ target }}"
                data:
                  file:
                    path: "{{ filePath }}"
        # If a URL is set.
        - conditions:
            - condition: template
              value_template: "{{ filePath is not defined and url is defined }}"
          sequence:
            # Check if a title has been set
            - choose:
                # Check at least filePath or url is set.
                - conditions:
                    - condition: template
                      value_template: "{{ title is defined }}"
                  sequence:
                    - service: notify.slack_notify
                      data:
                        message: "{{ message }}"
                        title: "{{ title|default('', true) }}"
                        target: "{{ target }}"
                        data:
                          blocks:
                            - type: header
                              text:
                                type: "plain_text"
                                text: "{{ title }}"
                                emoji: true
                            - type: section
                              text:
                                type: mrkdwn
                                text: "{{ message }}"
                              accessory:
                                type: image
                                image_url: "{{ url }}"
                                alt_text: "{{ title|default('Failed to load image', true) }}"
              # No title set
              default:
                - service: notify.slack_notify
                  data:
                    message: "{{ message }}"
                    title: "{{ title|default('', true) }}"
                    target: "{{ target }}"
                    data:
                      blocks:
                        - type: section
                          text:
                            type: mrkdwn
                            text: "{{ message }}"
                          accessory:
                            type: image
                            image_url: "{{ url }}"
                            alt_text: "{{ title|default('Failed to load image', true) }}"
        default:
          # No title set
          - service: notify.slack_notify
            data:
              message: "{{ message }}"
              target: "{{ target }}"
              data:
                blocks:
                  - type: section
                    text:
                      type: plain_text
                      text: "{{ message }}"
                    accessory:
                      type: image
                      image_url: "{{ url }}"
                      alt_text: "{{ title|default('Failed to load image', true) }}"
    mode: queued
    max: 10
```
