### ISSUE TITLE
Create a ⏱️Stopwatch For 🍳 Oven

### ISSUE THREAD

**Issue by dannytsang** [dannytsang/homeassistant-config#97]
When the oven is in use, create 2 clocks for how long the oven has been on for.

* [x] From when it turns on.
* [x] After pre-heat.

Most items need the oven to be pre-heated before putting the item in so it would not make sense to have 2 separate clocks.

It would be hard to automate a timer because Home Assistant would need to know when the item was put in as well as how long for. It would be quicker to set a timer on the oven or some other device at this stage.

**Comment by dannytsang** [comment]
Turns out, a stopwatch is not a feature in Home Assistant ☹️ workaround: https://community.home-assistant.io/t/stopwatch-with-start-stop-resume-lap-and-reset/443994

**Comment by dannytsang** [comment]
Added helper and automations for preheat detection: e53897c70b1a34403ba9beb7193ca4f29b3ad849

Using chip card from mushroom integration, a chip appears when the oven is on. The colour and time last changed will change depending if it's preheating or preheated. This will mean the time shown will reset when the preheat is done.

``` YAML
type: custom:mushroom-chips-card
chips:
  - type: conditional
    conditions:
      - entity: binary_sensor.oven_powered_on
        state: 'on'
    chip:
      type: template
      entity: binary_sensor.oven_powered_on
      icon: mdi:toaster-oven
      icon_color: >-
        {{ iif(states('input_boolean.oven_preheated') == 'on', 'green',
        'orange') }}
      content: >-
        Oven ({{ iif(states('input_boolean.oven_preheated') == 'on',
        relative_time(states.input_boolean.oven_preheated.last_changed),
        relative_time(states.binary_sensor.oven_powered_on.last_changed)) }})
      tap_action:
        action: more-info
```
Example look and feel:
![image](https://github.com/dannytsang/homeassistant-config/assets/567982/9c85247d-aff9-4b2c-a227-c40f189a89d0)
![image](https://github.com/dannytsang/homeassistant-config/assets/567982/4ab9ff61-0a25-4a34-8b27-d9399f5d5690)
