### ISSUE TITLE
Assist For Solar

### ISSUE THREAD

**Issue by dannytsang** [dannytsang/homeassistant-config#99]
Add Home Assistant Assist for solar related information and actions. Some already exists so these are new ideas.

* [ ] Changing mode - export, battery, grid
* [ ] Current and next unit rate

**Comment by dannytsang** [comment]
Parking this for now. Custom sentences seems flaky.

For example:

```
language: "en"
intents:
  abc:
    data:
      - sentences:
          - "[How much] battery [is] left"
  getBatteryLevel:
    data:
      - sentences:
          - "How long will the battery last"

intent_script:
  abc:
    speech:
      text: "Test"
  getBatteryLevel:
    speech:
      text: "{{ states('sensor.growatt_sph_battery_state_of_charge', with_unit=True) }}"
```

*How long will the battery last* will work yet when I swap the intent around:
```
# Created by Danny Tsang <danny@tsang.uk>
language: "en"
intents:
  abc:
    data:
      - sentences:
          - "How long will the battery last"
  getBatteryLevel:
    data:
      - sentences:
          - "[How much] battery [is] left"

intent_script:
  abc:
    speech:
      text: "Test"
  getBatteryLevel:
    speech:
      text: "{{ states('sensor.growatt_sph_battery_state_of_charge', with_unit=True) }}"

```
and asking assist *How long will the battery last* it will not work. I tried separating each intent and intent_script to a separate file, intent name and still cannot get it to work.
